In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
!pip install imblearn

In [14]:
os.getcwd()

'C:\\Users\\Sandy\\Desktop\\Geek_Lurn\\Python_files'

In [2]:
input_file = "C:/Users/Sandy/Desktop/Geek_Lurn/Data_set/"

In [3]:
logistic_data = pd.read_excel(input_file+"Logistic_Reg_Batch57.xlsx")

In [4]:
from sklearn.linear_model import LogisticRegression


In [5]:
import statsmodels.api as sm


In [6]:
logistic_data.head()

Ind_Exp_Act_Score  Tran_Speed_Score  Peer_Comb_Score  Outcome
0                6.2               9.3              7.4        1
1                2.6               2.2              8.7        1
2                9.5               1.5              8.2        1
3                2.6               5.0              0.4        0
4               10.0               7.7              7.2        1

In [7]:
logistic_data.Outcome.value_counts()

1    709
0    271
Name: Outcome, dtype: int64

In [8]:
x = logistic_data.iloc[:, 0:3]
y = logistic_data.Outcome


In [9]:
x["Intercept"]=1


In [10]:
#Developing the model
mymodel = sm.Logit(y,x)
myresult = mymodel.fit()
myresult.summary()


Optimization terminated successfully.
         Current function value: 0.064710
         Iterations 12


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  980
Model:                          Logit   Df Residuals:                      976
Method:                           MLE   Df Model:                            3
Date:                Mon, 20 Feb 2023   Pseudo R-squ.:                  0.8903
Time:                        20:20:05   Log-Likelihood:                -63.416
converged:                       True   LL-Null:                       -577.85
Covariance Type:            nonrobust   LLR p-value:                9.799e-223
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Ind_Exp_Act_Score     2.7957      0.355      7.867      0.000       2.099       3.492
Tran_Speed_Score      2.7532      0.343      8.032      0.000       2.081       3.425
Peer_Comb_Score       3.5153      0.434      8.095      0.000       2.664       4.366
Intercept           -35.5062      4.406     -8.058      0.000     -44.142     -26.870
=====================================================================================

Possibly complete quasi-separation: A fraction 0.62 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [11]:
pred = myresult.predict(x)

In [12]:
myoutput = pd.DataFrame(pred)
myoutput.to_csv("logistic_output.csv")

In [24]:
pred

0      1.000000
1      0.999776
2      1.000000
3      0.000002
4      1.000000
         ...   
975    0.046811
976    1.000000
977    0.000404
978    0.000098
979    0.075612
Length: 980, dtype: float64

In [12]:
predclass = [1 if i >= 0.5 else 0 for i in pred]


In [14]:
myoutput = pd.DataFrame(predclass)
myoutput.to_csv(input_file+"Logistic_output.csv")

In [19]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
pred_treshold_3 = [1 if i >=0.3 else 0 for i in pred]

In [23]:
print(confusion_matrix(pred_treshold_3,y))

[[246   8]
 [ 25 701]]


In [17]:
print(confusion_matrix(y,predclass))

[[257  14]
 [ 14 695]]


In [25]:
print(classification_report(y,pred_treshold_3))

              precision    recall  f1-score   support

           0       0.97      0.91      0.94       271
           1       0.97      0.99      0.98       709

    accuracy                           0.97       980
   macro avg       0.97      0.95      0.96       980
weighted avg       0.97      0.97      0.97       980



In [18]:
print(classification_report(y, predclass))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95       271
           1       0.98      0.98      0.98       709

    accuracy                           0.97       980
   macro avg       0.96      0.96      0.96       980
weighted avg       0.97      0.97      0.97       980



In [15]:
x.shape

(980, 4)

In [60]:
# split a dataset into train and test sets

from sklearn.model_selection import train_test_split
# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(686, 3) (294, 3) (686,) (294,)


In [1]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [28]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(686, 4) (294, 4) (686,) (294,)


In [61]:
y.value_counts()

1    709
0    271
Name: Outcome, dtype: int64

In [62]:
y_train.value_counts()

1    500
0    186
Name: Outcome, dtype: int64

In [63]:
y_test.value_counts()

1    209
0     85
Name: Outcome, dtype: int64

In [14]:
from sklearn.linear_model import LogisticRegression
lgm = LogisticRegression()

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
lgm = LogisticRegression()

In [15]:
lgm.fit(X_train,y_train)

LogisticRegression()

In [16]:
y_pred_test = lgm.predict(X_test)

In [17]:
y_pred_test

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix

In [20]:
y_pred_train = lgm.predict(X_train)

In [21]:
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.93      0.92      0.93       186
           1       0.97      0.98      0.97       500

    accuracy                           0.96       686
   macro avg       0.95      0.95      0.95       686
weighted avg       0.96      0.96      0.96       686



In [22]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       1.00      0.95      0.98        85
           1       0.98      1.00      0.99       209

    accuracy                           0.99       294
   macro avg       0.99      0.98      0.98       294
weighted avg       0.99      0.99      0.99       294



In [27]:
print(confusion_matrix(y_test, y_pred))

[[ 81   6]
 [  5 202]]


In [64]:
###### Under sampling & Over sampling

from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler 


In [65]:
# Randomly under sample the majority class
rus = RandomUnderSampler(random_state=42)
X_train_rus, y_train_rus= rus.fit_resample(X_train, y_train)


In [66]:
y_train.value_counts()

1    500
0    186
Name: Outcome, dtype: int64

In [67]:
y_train_rus.value_counts()

0    186
1    186
Name: Outcome, dtype: int64

In [68]:
# Randomly over sample the minority class
ros = RandomOverSampler(random_state=42)
X_train_ros, y_train_ros= ros.fit_resample(X_train, y_train)


In [69]:
y_train_ros.value_counts()

1    500
0    500
Name: Outcome, dtype: int64

In [30]:
from imblearn.over_sampling import SMOTE

In [75]:
# Randomly over sample the minority class
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote= smote.fit_resample(X_train, y_train)


In [76]:
y_train_smote.value_counts()

1    500
0    500
Name: Outcome, dtype: int64

In [70]:
data_over_sampling = pd.concat([X_train,y_train],axis=1)

In [71]:
data_over_sampling.shape

(686, 4)

In [38]:
c.head()

Ind_Exp_Act_Score  Tran_Speed_Score  Peer_Comb_Score  Outcome
49                 1.5               8.0              1.3        0
290                5.5               1.6              0.6        0
63                 7.4               8.4              2.8        1
237                7.5               8.0              6.4        1
801               10.0               7.7              1.7        1

In [72]:
data_over_sampling_ros = pd.concat([X_train_ros, y_train_ros],axis=1)

In [77]:
data_over_sampling_smote = pd.concat([X_train_smote, y_train_smote],axis=1)

In [74]:
data_over_sampling_ros.to_csv("oversmapling_example.csv")

In [79]:
data_over_sampling_smote.to_csv("smote_example.csv")

In [46]:
os.getcwd()

'C:\\Users\\Sandy\\Desktop\\Geek_Lurn\\Python_files'